FROM node:16.0.0-alpine as node

FROM golang:1.16.3-alpine
ENV GOCACHE=/usr/local/go/src/coach/.cache/go-build
ENV GOBIN=/usr/local/go/bin
ENV GO111MODULE=on
ENV CGO_ENABLED=0
RUN apk update\
    && apk add --no-cache --update git curl python3 make g++
COPY --from=node /usr/local/bin/node /usr/local/bin/
COPY --from=node /usr/local/lib/node_modules/ /usr/local/lib/node_modules/
RUN ln -s /usr/local/bin/node /usr/local/bin/nodejs \
    && ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.11.0/migrate.linux-amd64.tar.gz | tar xvz \
    && mv ./migrate.linux-amd64 /usr/bin/migrate
WORKDIR /app