FROM golang:1.16.3-alpine
RUN apk update \
    && apk add git

RUN echo 'root:root' |chpasswd
RUN adduser -S nao \
    && echo "nao ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers \
    && echo "nao:nao" | chpasswd