version: '3.7'
services:
  development:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile.dev
    tty: true
    volumes:
      - .:/app
    ports:
      - ${API_PORT:-8080}:${API_PORT:-8080}
      - ${NUXT_ENV_FRONT_PORT:-3000}:${NUXT_ENV_FRONT_PORT:-3000}
    stdin_open: true
    environment:
      - DB_DRIVER_NAME=${DB_DRIVER_NAME:-mysql}
      - DB_NAME=${DB_NAME:-coach_db}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_USER_PASSWORD=${DB_USERPASSWORD:-root}
      - DB_HOST=${DB_HOST:-coach_db_dev}
      - DB_PORT=${DB_PORT:-3306}
      - API_PORT=${API_PORT:-8080}
      - NUXT_ENV_HOST=${NUXT_ENV_HOST:-localhost}
      - NUXT_ENV_FRONT_PORT=${NUXT_ENV_FRONT_PORT:-3000}
      - HOST=localhost
      - FRONT_PORT=3000
      - NUXT_ENV_APP_HOST=${NUXT_ENV_APP_HOST:-localhost}
      - NUXT_ENV_API_PORT=${NUXT_ENV_API_PORT:-8080}
    env_file: .env
  coach_db_dev:
    image: mysql:8.0.26
    restart: always
    ports:
      - ${DB_PORT:-3306}:${DB_PORT:-3306}
    volumes:
      - ./backend/db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./backend/db/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    env_file: .env.dev.db
