version: '3.7'
services:
  backend_prod:
    image: ghcr.io/naoki-urabe/coach/api:prod
    tty: true
    stdin_open: true
    depends_on:
      - coach_db_prod
    ports:
      - $API_PORT:$API_PORT
    env_file:
      .env.prod.api
  front_prod:
    image: ghcr.io/naoki-urabe/coach/front:prod
    tty: true
    ports:
      - $NUXT_ENV_FRONT_PORT:$NUXT_ENV_FRONT_PORT
    env_file:
      .env.prod.front
  task:
    image: ghcr.io/naoki-urabe/coach/task:prod
    depends_on:
      - coach_db_prod
    env_file:
      .env.prod.api
  coach_db_prod:
    image: mysql:8.0.26
    restart: always
    ports:
        - $DB_PORT:$DB_PORT
    volumes:
      - ./backend/db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./backend/db/mysql_data:/var/lib/mysql
    env_file: .env.prod.db
