version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.api
    tty: true
    volumes:
      - .:/app
    ports:
      - 59822:59822
    stdin_open: true
    env_file: .env.dev.api
  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile.front
    tty: true
    volumes:
      - .:/app
    depends_on:
      - backend
    ports:
      - 55824:55824
    env_file: .env.dev.front
  coach_db_dev:
    image: mysql:8.0.26
    restart: always
    ports:
      - 50284:50284
    volumes:
      - ./backend/db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./backend/db/mysql_data:/var/lib/mysql
    env_file: .env.dev.db