name: CI/CD
on:
  push:
    branches:
      - master
env:
  API_IMAGE: ghcr.io/naoki-urabe/coach/api:prod
  FRONT_IMAGE: ghcr.io/naoki-urabe/coach/front:prod
  TASK_IMAGE: ghcr.io/naoki-urabe/coach/task:prod
jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: set environemnt variable
        run: |
          echo "API_PORT=${{ secrets.API_PORT }}" >> $GITHUB_ENV
          echo "FRONT_PORT=${{ secrets.FRONT_PORT }}" >> $GITHUB_ENV
          echo "MYSQL_PORT=${{ secrets.MYSQL_TCP_PORT }}" >> $GITHUB_ENV
      - name: Add environment variable to .env.prod
        run: |
          echo MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env.prod.db
          echo MYSQL_DATABASE="${{ secrets.MYSQL_DATABASE }}" >> .env.prod.db
          echo MYSQL_TCP_PORT=55821 >> .env.prod.db
      - name: Add environment variable to .env.prod.api
        run: |
          echo API_PORT=57249 >> .env.prod.api
          echo DB_DRIVER_NAME=mysql >> .env.prod.api
          echo DB_NAME="${{ secrets.MYSQL_DATABASE }}" >> .env.prod.api
          echo DB_USERNAME=root >> .env.prod.api
          echo DB_USER_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env.prod.api
          echo DB_HOST=coach_db_prod >> .env.prod.api
          echo DB_PORT=55821 >> .env.prod.api
      - name: Add environment variable to .env.prod.front
        run: |
          echo NUXT_ENV_APP_HOST="${{ secrets.APP_HOST }}" >> .env.prod.front
          echo NUXT_ENV_API_PORT=57249 >> .env.prod.front
          echo NUXT_ENV_FRONT_PORT=53504 >> .env.prod.front
      - name: Add environment variable to .env.prod.front
        run: |
          echo NUXT_ENV_APP_HOST="${{ secrets.APP_HOST }}" >> front/.env
          echo NUXT_ENV_API_PORT=57249 >> front/.env
          echo NUXT_ENV_FRONT_PORT=53504 >> front/.env
      - name: Log in to Github packages
        run: echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build image
        run: |
          docker-compose -f docker-compose.ci.yml build
      - name: push image
        run: |
          docker push ${{ env.API_IMAGE }}
          docker push ${{ env.FRONT_IMAGE }}
          docker push ${{ env.TASK_IMAGE }}
      - name: install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: deploy
        run: bash deploy.sh
        env:
          HOST: ${{ secrets.HOST_NAME }}
          USER: ${{ secrets.USER }}
          HOST_PORT: ${{ secrets.HOST_PORT }}